/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GoChart {
    'clearSelection': () => void;
    'data': object[];
    'first': string;
    'last': string;
    'middle': string;
  }
  interface GoChartAttributes extends StencilHTMLAttributes {
    'data'?: object[];
    'first'?: string;
    'last'?: string;
    'middle'?: string;
    'onGoSelectEvent'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GoChart': Components.GoChart;
  }

  interface StencilIntrinsicElements {
    'go-chart': Components.GoChartAttributes;
  }


  interface HTMLGoChartElement extends Components.GoChart, HTMLStencilElement {}
  var HTMLGoChartElement: {
    prototype: HTMLGoChartElement;
    new (): HTMLGoChartElement;
  };

  interface HTMLElementTagNameMap {
    'go-chart': HTMLGoChartElement
  }

  interface ElementTagNameMap {
    'go-chart': HTMLGoChartElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
