/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  GOChartData,
} from './utils';

export namespace Components {
  interface GoChart {
    'clearSelection': () => Promise<void>;
    'data': GOChartData[];
    'selected': () => Promise<GOChartData[]>;
  }
}

declare global {


  interface HTMLGoChartElement extends Components.GoChart, HTMLStencilElement {}
  var HTMLGoChartElement: {
    prototype: HTMLGoChartElement;
    new (): HTMLGoChartElement;
  };
  interface HTMLElementTagNameMap {
    'go-chart': HTMLGoChartElement;
  }
}

declare namespace LocalJSX {
  interface GoChart extends JSXBase.HTMLAttributes<HTMLGoChartElement> {
    'data'?: GOChartData[];
    'onGo-chart.select'?: (event: CustomEvent<{ status: boolean, id: string, selected: GOChartData[] }>) => void;
  }

  interface IntrinsicElements {
    'go-chart': GoChart;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


